// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Owen Debiasio
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

use crate::utils::fs::{
    core::{read_file_to_string, write_to_file},
    paths::PATHS,
};

const AUTO_GEN: &str = "\
# Auto-generated by cmdcreate
#
# You can find available configurations at:
# https://github.com/owen-debiasio/cmdcreate/blob/main/docs/resources/config_example.toml\n
";

pub fn init_configs() {
    let config_file_path = &PATHS.configuration_file;
    let config_file_contents = read_file_to_string(config_file_path);

    if !config_file_contents.is_empty() {
        return;
    }

    write_to_file(config_file_path, AUTO_GEN, false);
}
