use toml::{Value, from_str};

use crate::utils::{
    fs::{create_file, path_exists, read_file_to_string, write_to_file},
    sys::VARS,
};

pub fn load(cat: &str, var: &str, or_else: &str) -> String {
    let data: Value = from_str(&read_file_to_string(&format!(
        "{}/.config/cmdcreate/config.toml",
        VARS.home
    )))
    .unwrap();

    data.get(cat)
        .and_then(|pkg| pkg.get(var))
        .and_then(|v| v.as_str())
        .unwrap_or(or_else)
        .to_string()
}

pub fn init_configs() {
    let file = &format!("{}/.config/cmdcreate/config.toml", VARS.home);

    if !path_exists(file) {
        create_file(file);

        for line in [
            "# This file has been auto-generated by cmdcreate\n",
            "# For all avaliable configurations, visit:\n",
            "# https://github.com/owen-debiasio/cmdcreate/blob/main/config_example.toml",
        ] {
            write_to_file(file, line);
        }
    }
}
