use toml::{Value, from_str};

use crate::utils::fs::{
    PATHS, create_file, create_folder, path_exists, read_file_to_string, write_to_file,
};

pub fn load(cat: &str, var: &str, or_else: &str) -> String {
    let data: Value = from_str(&read_file_to_string(&PATHS.configs)).unwrap();

    data.get(cat)
        .and_then(|pkg| pkg.get(var))
        .and_then(|v| v.as_str())
        .unwrap_or(or_else)
        .to_string()
}

pub fn init_configs() {
    if !path_exists(&PATHS.configs) {
        create_folder(&PATHS.configs);

        let file = &format!("{}/config.toml", PATHS.configs);

        create_file(file);

        for line in [
            "# This file has been auto-generated by cmdcreate\n",
            "# For all avaliable configurations, visit:\n",
            "# https://github.com/owen-debiasio/cmdcreate/blob/main/config_example.toml",
        ] {
            write_to_file(file, line);
        }
    }
}
