// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Owen Debiasio
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

use std::{fs::read_to_string, sync::LazyLock};

use toml::{map::Map, Value};

use crate::utils::fs::{overwrite_file, path_exists, PATHS};

const AUTO_GEN: &str = "
# Auto-generated by cmdcreate
#
# You can find available configurations at:
# https://github.com/owen-debiasio/cmdcreate/blob/main/docs/resources/config_example.toml
";

pub fn init_configs() {
    if path_exists(&PATHS.configs) {
        return;
    }

    overwrite_file(&PATHS.configs, AUTO_GEN).expect("Failed to overwrite file");
}

static CONFIG: LazyLock<Value> = LazyLock::new(|| {
    read_to_string(&PATHS.configs)
        .ok()
        .and_then(|s| s.parse::<Value>().ok())
        .unwrap_or_else(|| Value::Table(Map::default()))
});

pub fn load(cat: &str, var: &str, default: &str) -> String {
    CONFIG
        .get(cat)
        .and_then(|c| c.get(var))
        .and_then(|v| v.as_str())
        .unwrap_or(default)
        .to_string()
}
