name: Bash Lint

on:
  push:
    paths:
      - "**.sh"
  pull_request:
    paths:
      - "**.sh"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y shfmt shellcheck

      - name: shfmt (format check)
        run: |
          shfmt -d -i 4 -ci -sr .

      - name: shellcheck
        run: |
          shellcheck $(git ls-files '*.sh')
