# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Owen Debiasio
# Licensed under the GNU General Public License v3.0 or later.

# This file is located in /etc/cmdcreate.toml

[sys]
shell = "bash" # Your preferred shell

[logs]
time_format = "%Y-%m-%d %H:%M:%S" # Formatting of time
verbose = "false" # If "true", logs will be printed to output

[appearance]
favorite_indicator = "★" # A symbol or string of text to indicate a favorite command
disable_color = "true" # If "true", colorized output will be disabled
