# Copyright (C) 2026 Owen Debiasio
# Licensed under the GNU General Public License v3.0 or later.
# Full notice available in the root README.md or COPYING file.

# This file is located in /root/.config/cmdcreate/config.toml

[sys]
shell = "bash" # Your preferred shell

[logs]
time_format = "%Y-%m-%d %H:%M:%S" # Formatting of time
verbose = "false" # If "true", logs will be printed to output

[appearence]
favorite_indicator = "★" # A symbol or string of text to indicate a favorite command